### ISSUE TITLE
DFA误杀率高

### ISSUE THREAD

**Issue by LtD0gE** [sudoskys/Openaibot#102]
当前方案：违禁词排除列表  日志回显被屏蔽内容
咕咕咕咕咕咕咕 guuu~~~ gugu

**Comment by sudoskys** [comment]
已经解决了这个问题，移除了常用词词库。

**Comment by sudoskys** [comment]
在上上上上上次提交

**Comment by sudoskys** [comment]
至于违禁词屏蔽回显，加一行日志输出即可

**Comment by LtD0gE** [comment]
> 已经解决了这个问题，移除了常用词词库。

但Open Ai Chat群里误杀现象依然很严重
可能是你忘了更新违禁词缓存（？

**Comment by sudoskys** [comment]
> > 已经解决了这个问题，移除了常用词词库。
> 
> 但Open Ai Chat群里误杀现象依然很严重 可能是你忘了更新违禁词缓存（？

请通知维护者更新实例到最新版本。
