### ISSUE TITLE
/chat /work 續寫

### ISSUE THREAD

**Issue by vst212** [sudoskys/Openaibot#117]
![image](https://user-images.githubusercontent.com/47769540/212527224-6dd897f6-1149-413e-bf6b-f47c5ad8c2c5.png)
抱歉請教
我用/chat 回答很奇怪
我用/work  回答正常了，但沒續寫功能
還想再問，不單/chat，哪回覆是自動回？
謝謝！

**Comment by sudoskys** [comment]
write 是续写，不能连续。
chat 是聊天，能连续。

**Comment by sudoskys** [comment]
chat 命令的回答很奇怪，是因为 语言预设 的问题，我会在下午进行简单修复，修复完毕我会关闭此Issue。

你可以使用 remind 命令来告诉它你需要使用英文对话。

**Comment by sudoskys** [comment]
私聊中直接发送默认使用 chat 模式，具体的命令列表在readme中，可以在botfather那里设置

**Comment by vst212** [comment]
還有個問題想請教，繁體中文支援嗎？

**Comment by sudoskys** [comment]
> 還有個問題想請教，繁體中文支援嗎？

当然支持

**Comment by sudoskys** [comment]
但是效果不是程序能够决定的，你用繁体中文提问，就会得到繁体的回复。

**Comment by vst212** [comment]
![image](https://user-images.githubusercontent.com/47769540/212527724-4cd816e6-c30d-4ce2-a543-4a167b948742.png)

我轉了用中文問，但回答很奇怪，跟問題完全不相關

**Comment by LtD0gE** [comment]
可能以前的遗留记忆把AI弄傻了（？
试试/forgetme 之后再问

**Comment by vst212** [comment]
![image](https://user-images.githubusercontent.com/47769540/212530676-1a1f48ef-3e24-4d1a-9335-b3a558d76599.png)

已重置🙈

**Comment by vst212** [comment]
我試過重新弄，保留config和重啟也是🙈

**Comment by sudoskys** [comment]
> ![image](https://user-images.githubusercontent.com/47769540/212527856-c42ee1f7-84b5-446f-9822-5e7d46b0c54d.png) 我轉了用中文問，但回答很奇怪，跟問題完全不相關

fixing
