### ISSUE TITLE
Telegram bot 无法回应群组匿名管理员

### ISSUE THREAD

**Issue by sider2vf** [sudoskys/Openaibot#124]
### 环境信息

> 系统：Debian 11
> Openaibot 版本：v1.5.9-alpha

### 遇到的问题
当我在群组中使用“匿名管理员”功能时，使用 /chat 命令会出现 OH no,api Outline or crash? 回复，在之前的旧版本中未遇到该问题

### 日志
```
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
2023-01-24 23:05:45,430 (async_telebot.py:543 MainThread) ERROR - TeleBot: "'trigger'"
2023-01-24 23:12:53.117 | ERROR    | App.Event:load_response:343 - RUN:Api Error:server_error:The server had an error while processing your request. Sorry about that!
```

**Comment by sudoskys** [comment]
是的，匿名管理员被认定为频道身份。

另外就是这个错误正在定位中

**Comment by sudoskys** [comment]
推荐先检查一下设置内容，比如trigger

**Comment by sider2vf** [comment]
trigger 打开以后在群内仍然无主动回复（包括普通成员发言），bot有权限访问聊天内容，log没有看到什么特别的

**Comment by sudoskys** [comment]
> 

正在测试

**Comment by sudoskys** [comment]
fixed

**Comment by sudoskys** [comment]
And https://github.com/sudoskys/Openaibot/issues/125

**Comment by sudoskys** [comment]
> 已经修正 app.toml 的拼写错误，但主动回复仍未工作，以下是有关日志
> 
> `Run time of job "BotRunner.run.<locals>.get_request_frequency (trigger: interval[0:00:04], next run at: 2023-01-25 08:09:09 EST)" was missed by 0:00:03.867678`

这个是正常的定时器消息，属于正常 Log,主动回复是在特定条件下才会发生，而且具有强制冷却的

**Comment by sider2vf** [comment]
主动回复触发时，依然报错 `OH no,api Outline or crash?` 
查看运行日志，显示内容为： `2023-01-26T02:29:59.202904-0500 - ERROR - RUN:Api Error:'dict' object has no attribute 'dict'`

**Comment by sudoskys** [comment]
> 主动回复触发时，依然报错 `OH no,api Outline or crash?` 查看运行日志，显示内容为： `2023-01-26T02:29:59.202904-0500 - ERROR - RUN:Api Error:'dict' object has no attribute 'dict'`

奇怪

**Comment by sudoskys** [comment]
依赖库和程序都要是最新的才行
