### ISSUE TITLE
智力低下

### ISSUE THREAD

**Issue by sider2vf** [sudoskys/Openaibot#129]
### 问题
使用AI联网查询功能（ `search` 插件和 `duckgo` 插件，均已正常工作），问了他一些名人的家庭关系问题，如： `你知道xxx的父亲是谁吗` 或者 `查询xxx的母亲是谁`，均触发了在线搜索关键词，服务器的IP并未被搜索引擎拉黑。如果再用 `/chat` 发起新对话重新问问题，他会回复相同的答案并开始犟嘴，如果使用 `/forgetme` 后再进行 `/chat` 他会给出另一段他自己编的内容。使用 `/remind` 设置的场景经常会被AI忘记，执行 `/forgetme` 后又正常。

### 环境
> _新闻:请使用 `pip install -U llm-kira -i https://pypi.org/simple/` `pip uninstall openai-kira`_ （已按照此新闻中的内容试过，然而并没有什么改变）
> 依赖库和程序都是最新版
> 此问题在切换到旧版本时有所改善

**Comment by sudoskys** [comment]
应该是传参传错了

**Comment by sudoskys** [comment]
然后remind被强制裁切掉了，这个，等来电修

**Comment by sider2vf** [comment]
另外，在群组中发起的 `/chat` 可能会出现多人的对话内容窜稀的问题，他会用和别人对话中的问题和记忆来回复你在群组中用 `/chat` 发起的新对话

**Comment by sudoskys** [comment]
fixed

**Comment by sudoskys** [comment]
> 



> 另外，在群组中发起的 `/chat` 可能会出现多人的对话内容窜稀的问题，他会用和别人对话中的问题和记忆来回复你在群组中用 `/chat` 发起的新对话

那个没有串，是特性啦

**Comment by sider2vf** [comment]
主动回复出现新报错

```
2023-01-27T03:05:41.627330-0500 - ERROR - RUN:Api Error:division by zero
2023-01-27T03:05:41.627662-0500 - ERROR - argument of type 'ZeroDivisionError' is not iterable
```

**Comment by sudoskys** [comment]
不知道具体哪一行，但是修了修

**Comment by sudoskys** [comment]
更新依赖库到 0.2.2 吧，我发现之前的版本的记忆桶是倒转的

**Comment by sider2vf** [comment]
以及它对许多名人的生卒年份都有错误，具体表现为离正确的差一年（有时候连着出生地也一起乱编），但是生平简介和Wiki上的一模一样（这是联网了但没有完全联网嘛？好怪哦）

**Comment by sudoskys** [comment]
> 



> 以及它对许多名人的生卒年份都有错误，具体表现为离正确的差一年（有时候连着出生地也一起乱编），但是生平简介和Wiki上的一模一样（这是联网了但没有完全联网嘛？好怪哦）

不懂唉

**Comment by sider2vf** [comment]
> > 
> 
> > 以及它对许多名人的生卒年份都有错误，具体表现为离正确的差一年（有时候连着出生地也一起乱编），但是生平简介和Wiki上的一模一样（这是联网了但没有完全联网嘛？好怪哦）
> 
> 不懂唉

比如询问他丁真的信息，他可能会乱编丁真的出生地，出生日期的年份经常有一年的误差，后面会跟着依托答辩

**Comment by sudoskys** [comment]
应该是信息不够，这点没有办法，实时功能需要一个新的算法来增强，它并不总准确

**Comment by sudoskys** [comment]
> 



> 联网搜索功能出现了抽象问题，大多数时候是只能对前一半，后一半错得离谱，这个更抽象，直接把广告什么的东西也包含了
> 
> ![image](https://user-images.githubusercontent.com/116246824/215060100-f8f0c867-59cf-4b65-933d-ec9d75ce5bdf.png)

要看你用什么引擎了

**Comment by sudoskys** [comment]
https://github.com/sudoskys/Openaibot/commit/d7d7c1f1c90235f11564ad24c772e8d81ff2c20e
