### ISSUE TITLE
多生成端配置

### ISSUE THREAD

**Issue by sudoskys** [sudoskys/Openaibot#132]

**Comment by sudoskys** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/524

**Comment by sudoskys** [comment]
**https://github.com/sudoskys/Openaibot/commit/09336da419a9967e49752eed72a55e2bb964398a**

**Comment by sudoskys** [comment]
https://github.com/sudoskys/Openaibot/issues/19#issuecomment-1410012936

**Comment by sudoskys** [comment]
service.json 
```json
  "backend": {
    "model": "something"
  },
```

**Comment by Zoumachuan** [comment]
您好，想问一下如何更换模型呢？在git好的文件里没有找到service.json，是需要自己新建一个吗？

**Comment by sudoskys** [comment]
> 您好，想问一下如何更换模型呢？在git好的文件里没有找到service.json，是需要自己新建一个吗？

是的

**Comment by sudoskys** [comment]
> 您好，想问一下如何更换模型呢？在git好的文件里没有找到service.json，是需要自己新建一个吗？

在项目 Config 中新建
