### ISSUE TITLE
prompt截取时仅有对话中第二个字

### ISSUE THREAD

**Issue by Zxis233** [sudoskys/Openaibot#14]
与机器人对话，发现输出的内容基本一致且无意义。观察控制台输出，发现prompt后为发送消息的第二个字。不论输入何种语言均为这样。
![image](https://user-images.githubusercontent.com/91776041/206193764-1d2ec9ab-2035-4c7f-8cad-e7590235c3e7.png)

**Comment by sudoskys** [comment]
怎么会

**Comment by sudoskys** [comment]
我写bug了

**Comment by sudoskys** [comment]
修复了
