### ISSUE TITLE
master user id &owner 具体指什么

### ISSUE THREAD

**Issue by moguv587** [sudoskys/Openaibot#16]
麻烦说明下，感谢

**Comment by sudoskys** [comment]
你的账号 Id

**Comment by socekin** [comment]
> 你的账号 Id

请问是指telegram的user ID 吗？@xxx?

**Comment by sudoskys** [comment]
> > 你的账号 Id
> 
> 请问是指telegram的user ID 吗？@xxx?

你的账户 ID 
在这里看 ：https://t.me/JsonDumpBot
