### ISSUE TITLE
问一下现在OpenAI的计费是怎么样的？

### ISSUE THREAD

**Issue by noname01t1** [sudoskys/Openaibot#19]
我昨天跑了一下，好像没被扣费，不知道是不是OpenAI的bug，因为当时试用18美金都还没给。今天才给上。

所以问一下就https://openai.com/api/pricing/ 上面的价格，现在费用是$0.0200/ 1K tokens吗？

**Comment by byferdu** [comment]
是500汉字0.02刀吧？

**Comment by sudoskys** [comment]
> 是500汉字0.02刀吧？

啊对，已改正

**Comment by aiastia** [comment]
话说能加入 别的模型吗 

我看 Curie $0.0020  / 1K tokens
Babbage $0.0005  / 1K tokens
Ada $0.0004  / 1K tokens
https://openai.com/api/pricing/#faq-search-pricing

**Comment by sudoskys** [comment]
> 话说能加入 别的模型吗
> 
> 我看 Curie $0.0020 / 1K tokens Babbage $0.0005 / 1K tokens Ada $0.0004 / 1K tokens https://openai.com/api/pricing/#faq-search-pricing

可以，最近在考虑多生成端点
