### ISSUE TITLE
运行就死机了~

### ISSUE THREAD

**Issue by Mabisi** [sudoskys/Openaibot#41]
![image](https://user-images.githubusercontent.com/19968269/207092629-bee70055-55dd-43f5-9199-c37f803c929c.png)

每次都卡在这里，重启程序也不行~~哪里有问题呀？

**Comment by sudoskys** [comment]
没卡，在等待消息

**Comment by sudoskys** [comment]
后台运行需要 nohup

**Comment by Mabisi** [comment]
> 没卡，在等待消息

一天了还是在这，机器人发送消息没反应！
![image](https://user-images.githubusercontent.com/19968269/207360472-73327d98-cf36-46ac-8e10-41fd93db2189.png)

**Comment by sudoskys** [comment]
> > 没卡，在等待消息
> 
> 一天了还是在这，机器人发送消息没反应！ ![image](https://user-images.githubusercontent.com/19968269/207360472-73327d98-cf36-46ac-8e10-41fd93db2189.png)

你配置了 master 了吗？

**Comment by sudoskys** [comment]
可能是网络问题

**Comment by sudoskys** [comment]
因为甚至不报错

**Comment by sudoskys** [comment]
请再次确认是否正确按照 readme 中的内容配置

**Comment by sudoskys** [comment]
最好更新到最新版本

**Comment by Mabisi** [comment]
> 最好更新到最新版本

更换了一台服务器跑起来了，不确定是不是因为亚洲ip的原因
