### ISSUE TITLE
API提示错误。重新生成多次，依然提示错误。

### ISSUE THREAD

**Issue by nanyang888** [sudoskys/Openaibot#48]
ERROR - 弹出非法ApiKey: --type invalid_api_key --auth sk-N*******************************************8xbG
ERROR - RUN:Api Error:invalid_request_error:Incorrect API key provided: sk-N1PyD***************************************8xbG. You can find your API key at https://beta.openai.com.

API提示错误。重新生成多次，依然提示错误。

**Comment by sudoskys** [comment]
系统提示 Api Key 不对，你确定你的key有效？

**Comment by nanyang888** [comment]
有效的，我绑定信用卡付费后，重复生成了多次，都是这样。
在Telegram上，是使用/add_api_key +[API Key]，添加的。
添加后，/see_api_key是可以看到key的。这时log已经有非法提示。
此时，Telegram发送文字后，查看日志就API key missing。

**Comment by nanyang888** [comment]
另外，服务器是美国洛杉矶的Ubuntu系统，系统是干净的，除了Python3.8没有安装其他东西。
程序没有开启ip代理。我删除了config中的代理字段。

**Comment by sudoskys** [comment]
这个我这边无法复现.....这个非法是 Api 那边弹回的消息。
PS:代理字段只需要设定为 false 即可。

**Comment by sudoskys** [comment]
重新测试添加 key ，没有问题。应该是 Openai 那边的问题。

**Comment by alastone** [comment]
Error Occur~Maybe Api request rate limit~nya

**Comment by sudoskys** [comment]
> 
请查看控制台输出

**Comment by sudoskys** [comment]
> Error Occur~Maybe Api request rate limit~nya

请查看控制台输出

**Comment by baiminai** [comment]
> 请问这是什么意思，具体要怎么操作才能解决

**Comment by sudoskys** [comment]
@baiminai key 过期或无效
