### ISSUE TITLE
[Try] Web 额外支持

### ISSUE THREAD

**Issue by sudoskys** [sudoskys/Openaibot#57]
尝试提供实时的支持

**Comment by sudoskys** [comment]
似乎不适合大规模用。效果倒是不错

**Comment by zzh89982330** [comment]
求问web支持在代码的哪个地方呢，想要详细学习一下，之前尝试过接口逆向，但是发现加密和反机器人做得太足的放弃了，后来自己实现了一个纯模拟browser的机器人，能够运行但是人数稍多就寄了 :(，想知道楼主大大是怎么实现的
