### ISSUE TITLE
怎么把手机端的最下边的list,check,reborn去掉呢

### ISSUE THREAD

**Issue by yaovenus** [sudoskys/Openaibot#60]
占用手机屏幕的1/3
怎么去掉呢？
![Screenshot_2022-12-16-16-03-43-40_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/22662509/208052255-fc2ab93e-6cdf-46c6-a3a0-e1cdcaf23837.jpg)

**Comment by sider2vf** [comment]
这个是 Telegram 的问题吧，而且这个项目部署的 bot 并没有 `/list` `/check` `/reborn` 这几个命令

**Comment by sudoskys** [comment]
不是我的项目
